dist: trusty
language: java
jdk: oraclejdk8
notifications:
  email: false
env:
  global:
  - TERM=dumb

before_install: '[ "${TRAVIS_PULL_REQUEST}" != "false" ] || openssl aes-256-cbc -K $encrypted_0a5ad00a3b24_key -iv $encrypted_0a5ad00a3b24_iv -in keystore.jks.enc -out keystore.jks -d'
install: ./gradlew build -S

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.gradle'
before_cache:
    - rm -f $HOME/.gradle/caches/*/*.lock

branches:
  except:
  - /^release-.*$/

deploy:
  - provider: script
    skip_cleanup: true
    script: ./gradlew curseforge -S
    on:
      all_branches: true
      repo: CyclopsMC/Flopper
      tags: true
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: eNnAxw9cZB3S5s5Z1RXj7qUuWfClPdm+obV1mEHqYvTT4f6m7AY9z4b0OWSOsgyJ6tSEZmKmU5shfpVcOz/tMO5X+wYwkNoxYsyA1y8xJaq5JDdEQjtEVvAP1L4AuDdWzTMwHs/tkst0barakkNFg54D8HfCBqLD6rhepIP51Iu1MqUZPd5/1LIa2oiQ5wgwcl+VQ3cBT/l0aVTTEXsY3o2P7HMFxHkInj2IstlEwwcou0H4yEt2v1zY3u1u3FV71dDckwSeYRiJCjqCOS0+b/t9Hjn4O+yl9fA9rBu/jnW+JA8ARqgXjhZXs6RgzISOnNbpWUdvCBYEwUDN7LAqcpzBm8F8OfKpALlH4Ij2KTconVn3DTLP8GL9tEB565Btyy5ErQ/2InMe20zkJSTYuS+3WRiqryleqKNKrNsey/stY7LOPxr+ScD4kPihyg8St3s8LM3zdL7dM+xjWD4aNyeGyOyvaRWJXXAhWVtcQDySVzyE/LSEhuUFwqOvrIXE5TtlU+fpxIuqY9JNsKunR+mvDw3zSNo6J5tnXm7ETlBbY6o1R5OhzHxn/0k4JemJQLN5l7KBUJMqzgn+h5xLP2DQh45nfgCb+9zuIJ6Ce+/N4kjgUxZxa/5bmspv9FqA+gyxI35nojo660KPF5+iP43NXBg+93CTh9ACaSQLDjM=
    on:
      all_branches: true
      repo: CyclopsMC/Flopper
      tags: true
  - provider: script
    skip_cleanup: true
    script: ./gradlew uploadArchives -S
    on:
      all_branches: true
      repo: CyclopsMC/Flopper
      condition: "$TRAVIS_BRANCH =~ ^(master|release).*$"
