modLoader="javafml"
loaderVersion="[40,)"
issueTrackerURL="https://github.com/CyclopsMC/Flopper/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/flopper"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="flopper"
version="${file.jarVersion}"
displayName="Flopper"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/flopper.json"
description='''
Discover, share and conquer abilities that stick.
'''
[[dependencies.flopper]]
    modId="cyclopscore"
    mandatory=true
    versionRange="[1.13.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.flopper]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.flopper]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,]"
    ordering="NONE"
    side="BOTH"
