modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/CyclopsMC/Flopper/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/flopper"
license="MIT"
logoFile="logo.png"
authors="rubensworks (aka kroeser)"
[[mods]]
modId="flopper"
version="${file.jarVersion}"
displayName="Flopper"
updateJSONURL="https://raw.githubusercontent.com/CyclopsMC/Versions/master/forge_update/flopper.json"
description='''
Discover, share and conquer abilities that stick.
'''
[[dependencies.flopper]]
    modId="cyclopscore"
    type="required"
    versionRange="[1.19.10,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.flopper]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.flopper]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1,]"
    ordering="NONE"
    side="BOTH"
